import { type Module, inject } from 'langium';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices } from 'langium/lsp';
import { PineScriptGeneratedModule, PineScriptGeneratedSharedModule } from './generated/module.js';
import { PineScriptValidator, registerValidationChecks } from './pine-script-validator.js';
import { IndentationAwareLexer } from 'langium';
import { PineScriptTokenBuilder } from './pine-script-token-builder.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type PineScriptAddedServices = {
    validation: {
        PineScriptValidator: PineScriptValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type PineScriptServices = LangiumServices & PineScriptAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const PineScriptModule: Module<PineScriptServices, PartialLangiumServices & PineScriptAddedServices> = {
    validation: {
        PineScriptValidator: () => new PineScriptValidator()
    },
    parser: {
        TokenBuilder: () => new PineScriptTokenBuilder(),
        Lexer: (services) => new IndentationAwareLexer(services)
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createPineScriptServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    PineScript: PineScriptServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        PineScriptGeneratedSharedModule
    );
    const PineScript = inject(
        createDefaultModule({ shared }),
        PineScriptGeneratedModule,
        PineScriptModule
    );
    shared.ServiceRegistry.register(PineScript);
    registerValidationChecks(PineScript);
    return { shared, PineScript };
}
